name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: artifacts/*.zip
          extension-id: idfdgblnpifgahcomjiakagnhjgpgfik
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          glob: true
